//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int FavoriteId { get; set; }
        public int usesrsId { get; set; }
        public string FavType { get; set; }
        public string FavValue { get; set; }
    }
}
