//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsFeed
    {
        public int NewsId { get; set; }
        public string NewsHeader { get; set; }
        public string NewsImageUrl { get; set; }
        public string NewsBody { get; set; }
    }
}
